version: "3.3"
volumes:
  data:
services:
  db:
    container_name: smart-family-db
    image: "postgres:11"
    ports:
      - "6432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
